service: serverless

provider:
  name: aws
  runtime: nodejs8.10
  # profile: default
  region: us-west-1
  stage: dev

plugins:
  - serverless-offline


functions :
  helloworld:
    handler: src/helloworld.handler
